[doc]
name = "1995parham.pdf"
bundle = "https://data1.fullyjustified.net/tlextras-2022.0r0.tar"

# Default output (Turkey)
[[output]]
name = "parham"
type = "pdf"
tex_format = "latex"
shell_escape = true
preamble = ""
index = "main.tex"
postamble = ""

# Turkey variant
[[output]]
name = "parham-turkey"
type = "pdf"
tex_format = "latex"
shell_escape = true
preamble = ""
index = "turkey.tex"
postamble = ""

# Iran variant
[[output]]
name = "parham-iran"
type = "pdf"
tex_format = "latex"
shell_escape = true
preamble = ""
index = "iran.tex"
postamble = ""
